### ISSUE TITLE
Not working with listiview inside singleScrollview

### ISSUE THREAD

**Issue by iaohtdev** [LinXunFeng/flutter_scrollview_observer#34]
I'm trying use jump to, but it doesn't work

<img width="605" alt="Screenshot 2023-07-06 at 3 23 23 PM" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/95197224/6a477c50-ba7b-43f8-918a-235a892a6241">

**Comment by LinXunFeng** [comment]
Yes, because now the offset of `ScrollView` is controlled by the outer `SingleChildScrollView`. I think you should use `CustomScrollView` to implement your complex layout effect.

- Use `CustomScrollView` to replace `SingleChildScrollView`
- Use `SliverViewObserver` to replace `ListViewObserver`
- Use `SliverList` to replace `ListView`

Related usage example of SliverViewObserver: [custom_scrollview_demo_page.dart](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/example/lib/features/custom_scrollview/custom_scrollview_demo/custom_scrollview_demo_page.dart)
