### ISSUE TITLE
Animation duration

### ISSUE THREAD

**Issue by cyb3rsalih** [LinXunFeng/flutter_scrollview_observer#5]
I am using the package for a book that about 300 pages. When I want to go a spesific page, I am using 

` listObserverController.jumpTo(index: 150)` Which is going to 150th page.

But it took a while to go to the page when I am in page 5. The screen animating (emulating) a real scroll. I wait until it reach the point I enter. 

Is there a way to really Jump to the spesific index. Not animate.

**Comment by LinXunFeng** [comment]
Yes, the package will have the problem you mentioned, because it has to scroll close to the target position to know the offset, then the offset will be recorded, so there will be no animation when the second time jumping to the same index.

Is the height of the child widgets fixed? If so, you can adjust to rely on the `develop` branch, and use the `isFixedHeight` parameter to solve the problem you said, as follows:

```yaml
dependencies:
  scrollview_observer: 
    git: https://github.com/LinXunFeng/flutter_scrollview_observer.git
    ref: develop
```

```dart
listObserverController.jumpTo(index: 150, isFixedHeight: true); 
```


Related demo: [listview_fixed_height_demo](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/develop/example/lib/features/listview/listview_fixed_height_demo/listview_fixed_height_demo_page.dart)

**Comment by cyb3rsalih** [comment]
thanks. Unfortunately my pages are not have fixedsize. 
May be next days we may find some solutions.
It doensn't look bad for today. 

Have a nice day

**Comment by StigUK** [comment]
@cyb3rsalih Hello. Did you manage to find some solution when scrolling the list, where the height of the elements is not the same?

**Comment by LinXunFeng** [comment]
@cyb3rsalih Hello, you can use this package in conjunction with the cacheExtent property of scrollview. Assigning an appropriate value to cacheExtent can avoid unnecessary page turning. 

The recommendations are as follows:

- If child widgets are fixed height in scrollView, use `isFixedHeight` instead of `cacheExtent`.
- For scrollView such as detail page, it is recommended to set `cacheExtent` to `double.maxFinite`.
- If child widgets are dynamic height in scrollView, it is recommended that setting `cacheExtent` to a large and reasonable value depending on your situation.

For more information, please click the link [scrolling-to-the-specified-index-location](https://github.com/LinXunFeng/flutter_scrollview_observer#2scrolling-to-the-specified-index-location)
